// <auto-generated />
namespace LogIt.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Fooditem_Made_ModifiedBy_Not_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fooditem_Made_ModifiedBy_Not_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "202004041435379_Fooditem_Made_ModifiedBy_Not_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
