// <auto-generated />
namespace LogIt.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Made_ModifiedBy_Not_Required_For_All_Other_Tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Made_ModifiedBy_Not_Required_For_All_Other_Tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202004041438531_Made_ModifiedBy_Not_Required_For_All_Other_Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
